#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

echo "[policy] running..."
"${ROOT_DIR}/tests/policy/test_no_push_publish_workflow.sh"
"${ROOT_DIR}/tests/policy/test_ci_has_e2e_smoke_gate.sh"
"${ROOT_DIR}/tests/policy/test_e2e_real_workflow_opt_in.sh"
"${ROOT_DIR}/tests/policy/test_winebot_official_defaults.sh"
"${ROOT_DIR}/tests/policy/test_no_winebot_local_build_path.sh"
"${ROOT_DIR}/tests/policy/test_publish_dockerfiles_exist.sh"
"${ROOT_DIR}/tests/policy/test_publish_docker_base_policy.sh"
"${ROOT_DIR}/tests/policy/test_publish_image_contracts.sh"
"${ROOT_DIR}/tests/policy/test_publish_security_gates.sh"
"${ROOT_DIR}/tests/policy/test_container_fixture_paths.sh"
"${ROOT_DIR}/tests/policy/test_daemon_api_security_plan.sh"
"${ROOT_DIR}/tests/policy/test_daemon_auth_phase1_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_authz_phase2_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_transport_phase3_contract.sh"
"${ROOT_DIR}/tests/policy/test_signing_pki_helper_exists.sh"
"${ROOT_DIR}/tests/policy/test_daemon_pki_helper_exists.sh"
"${ROOT_DIR}/tests/policy/test_daemon_deploy_profile_doc.sh"
"${ROOT_DIR}/tests/policy/test_daemon_deploy_templates.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_integration.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_templates_smoke.sh"
"${ROOT_DIR}/tests/policy/test_daemon_serve_preflight_flag_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_status_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_counters_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_trend_report_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_trend_api_contract.sh"
"${ROOT_DIR}/tests/policy/test_daemon_preflight_trend_threshold_gate.sh"
"${ROOT_DIR}/tests/policy/test_submodule_bootstrap_flow.sh"
"${ROOT_DIR}/tests/policy/test_preflight_trend_gate_workflow_opt_in.sh"
"${ROOT_DIR}/tests/policy/test_commit_policy_documented.sh"
"${ROOT_DIR}/tests/policy/test_tla_idempotency_skeleton.sh"
"${ROOT_DIR}/tests/policy/test_tla_skeleton_workflow_opt_in.sh"
"${ROOT_DIR}/tests/policy/test_tla_extended_invariants_contract.sh"
echo "[policy] ok"
