#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

echo "[shell-unit] running..."
"${ROOT_DIR}/tests/shell/test_pull_first.sh"
"${ROOT_DIR}/tests/shell/test_build_pull_first.sh"
"${ROOT_DIR}/tests/shell/test_build_local_opt_in.sh"
"${ROOT_DIR}/tests/shell/test_winbuild_fixture_script.sh"
"${ROOT_DIR}/tests/shell/test_package_pull_first.sh"
"${ROOT_DIR}/tests/shell/test_package_local_opt_in.sh"
"${ROOT_DIR}/tests/shell/test_packaging_fixture_script.sh"
"${ROOT_DIR}/tests/shell/test_publish_dockerfiles_drycheck.sh"
"${ROOT_DIR}/tests/shell/test_publish_workflow_drycheck_order.sh"
"${ROOT_DIR}/tests/shell/test_sign_pull_first.sh"
"${ROOT_DIR}/tests/shell/test_sign_local_opt_in.sh"
"${ROOT_DIR}/tests/shell/test_dev_cert_lifecycle.sh"
"${ROOT_DIR}/tests/shell/test_signing_pki_lifecycle.sh"
"${ROOT_DIR}/tests/shell/test_sign_dev_cert_mode.sh"
"${ROOT_DIR}/tests/shell/test_smoke_trust_dev_cert.sh"
"${ROOT_DIR}/tests/shell/test_e2e_real_requires_installer.sh"
"${ROOT_DIR}/tests/shell/test_validate_installer_artifact.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_plan.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_idempotent.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_retry_resume.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_http_api.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_audit_log.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_store_migration.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_serve_auth_config.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_authz_policy.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_serve_tls_limits_config.sh"
"${ROOT_DIR}/tests/shell/test_wbabd_serve_preflight_flag.sh"
"${ROOT_DIR}/tests/shell/test_daemon_pki_lifecycle.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight_status_api.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight_audit_counters.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight_trend_report.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight_trend_api.sh"
"${ROOT_DIR}/tests/shell/test_daemon_preflight_trend_threshold_check.sh"
"${ROOT_DIR}/tests/shell/test_wbab_smoke_dispatch.sh"
"${ROOT_DIR}/tests/shell/test_wbab_package_dispatch.sh"
"${ROOT_DIR}/tests/shell/test_wbab_sign_dispatch.sh"
echo "[shell-unit] ok"
